"""PDF assembly utilities.

Right now this just does one thing: append a pre-rendered driving-directions
PDF onto the end of the prep handout so the scheduler hands the family a
single combined document.

The four directions PDFs live under `app/static/directions/`:
  - scc-directions.pdf   / scc-directions-es.pdf    (~1 MB each)
  - pmch-directions.pdf  / pmch-directions-es.pdf   (~800 KB each)

They're regenerated by the bowel-prep skill's `render_directions.py` and
copied here by `make sync-directions`. The originals live (and stay) in
~/Desktop/peds-gi-system/{loc}-directions[-es].pdf — these copies are the
container-image-bundled snapshot.

We accept that the appended pages keep their own page-numbering (the
prep portion still reads "page X of 3" in its footer, then the directions
footer kicks in for pages 4–N). Re-rendering directions per request to
unify the footer would defeat the static-cache win — see plan
Phase 2b "footer consistency: accept the seam".
"""
from __future__ import annotations

import io
from pathlib import Path

from pypdf import PdfReader, PdfWriter

DIRECTIONS_DIR = Path(__file__).resolve().parent / "static" / "directions"


def _directions_path(location_id: str, lang: str) -> Path:
    """Resolve the path for {location, lang}. Falls back to EN when ES is
    missing — keeps requests serving even if a translation slips behind."""
    suffix = "-es" if lang == "es" else ""
    candidate = DIRECTIONS_DIR / f"{location_id}-directions{suffix}.pdf"
    if candidate.exists():
        return candidate
    en_fallback = DIRECTIONS_DIR / f"{location_id}-directions.pdf"
    if en_fallback.exists():
        return en_fallback
    raise FileNotFoundError(
        f"No directions PDF for location={location_id!r} lang={lang!r}. "
        f"Looked under {DIRECTIONS_DIR}. Run `make sync-directions`."
    )


# Cache PdfReader objects at module load — these are static, small (~3.3 MB
# total across all four), and reusing them shaves the per-request merge from
# ~15 ms to ~5 ms. PdfReader holds an internal page index; pypdf is fine with
# the same reader being read by multiple writers across requests.
_READERS: dict[tuple[str, str], PdfReader] = {}


def _reader(location_id: str, lang: str) -> PdfReader:
    key = (location_id, "es" if lang == "es" else "en")
    if key not in _READERS:
        _READERS[key] = PdfReader(_directions_path(location_id, key[1]))
    return _READERS[key]


def append_directions(prep_pdf: bytes, location_id: str, lang: str) -> bytes:
    """Append the {location, lang} directions PDF to prep_pdf. Returns the
    merged bytes. ~5 ms on warm cache; the WeasyPrint render dwarfs it.

    The prep handout is rendered as a tagged PDF/UA-1 document (accessible
    structure tree, headings, tables). pypdf's plain ``append`` discards that
    structure tree, so we ``clone_document_from_reader`` the handout first —
    that preserves its tags — then ``append`` the directions map as a trailing
    appendix. The appendix pages themselves stay untagged (a pre-rendered map +
    address image; the same address also appears in the handout's tagged
    location section), which is a documented PDF/UA residual."""
    writer = PdfWriter()
    writer.clone_document_from_reader(PdfReader(io.BytesIO(prep_pdf)))
    writer.append(_reader(location_id, lang))
    buf = io.BytesIO()
    writer.write(buf)
    return buf.getvalue()
