#!/usr/bin/env python3
"""Generate the schedule-portal personalized print templates from the canonical
bowel-prep skill templates.

Why: The portal needs the same design as the canonical static handouts at
egdcolon.giready.com — yellow boxes, page-break cadence, MiraLAX wording — plus
a personalization layer (one-row appointment callout, pz-only heading suffixes,
pz-only inline date phrases) baked in for server-side WeasyPrint rendering.

Maintaining two parallel HTML templates by hand caused drift. This script makes
the personalized variants derived build artifacts of the canonical, so a fix in
~/.claude/skills/bowel-prep-generator/templates/ flows to the portal on the next
`make vendor-sync`.

Add new variants by writing a new patch function and wiring it in `main()`.
"""
from __future__ import annotations

import sys
from pathlib import Path

BACKEND_DIR = Path(__file__).resolve().parent.parent
VENDOR_TEMPLATES = BACKEND_DIR / "vendor" / "bowel-prep-generator" / "templates"
OUT_DIR = BACKEND_DIR / "app" / "templates" / "bowel_prep"

BANNER = (
    "<!-- GENERATED by scripts/build_personalized_templates.py — DO NOT HAND-EDIT.\n"
    "     Edit the canonical template at\n"
    "     ~/.claude/skills/bowel-prep-generator/templates/<name>.html\n"
    "     and/or this script's patch function, then re-run `make vendor-sync`. -->\n"
)


def _replace_unique(text: str, old: str, new: str, *, where: str) -> str:
    """Replace `old` with `new` in `text`. Raises if `old` doesn't appear
    exactly once — that way a stale patch fails loudly the next time the
    canonical template moves.
    """
    count = text.count(old)
    if count != 1:
        raise RuntimeError(
            f"patch '{where}' expected exactly 1 match for old string, got {count}.\n"
            f"old: {old!r}\n"
        )
    return text.replace(old, new, 1)


# -----------------------------------------------------------------------------
# Shared CSS injected into every print variant's <style> block.
# -----------------------------------------------------------------------------

_CSS_APPT_CALLOUT = """
  /* --- Personalized appointment callout (one-row, compact) ---------- */
  .appt-callout {
    margin: 3pt 0 6pt 0;
    padding: 4pt 9pt;
    background: #fff7d6;
    border-left: 3pt solid #f0b94c;
    border-radius: 2pt;
    page-break-inside: avoid;
  }
  .appt-line { font-size: 10pt; line-height: 1.35; color: #1a1a1a; }
  .appt-line strong { color: #0e2233; }
  .appt-label { color: #555; font-size: 9pt; }
  .appt-sep { color: #aaa; margin: 0 5pt; }
  /* --- Performing-physician callout (personalized handout only) ----- */
  .performing-physician {
    font-family: "Inter", sans-serif;
    font-size: 10pt;
    font-weight: 500;
    color: #555;
    margin-top: 3pt;
  }
  /* --- Standalone narrow follow-up appointment callout -------------- */
  .followup-callout {
    margin: 6pt 0; padding: 5pt 11pt;
    border-left: 3pt solid #0e4a82;
    background: #f5f8fb;
    display: flex; align-items: baseline; gap: 8pt;
    page-break-inside: avoid;
  }
  .followup-callout .followup-label {
    font-size: 8.5pt; text-transform: uppercase; letter-spacing: 0.04em;
    color: #555; font-weight: 600;
  }
  .followup-callout .followup-value {
    font-family: "Source Serif 4", Georgia, serif;
    font-size: 11pt; font-weight: 600; color: #0e2233;
  }
  .followup-callout.fallback .followup-value {
    font-family: "Inter", sans-serif;
    font-size: 10pt; font-weight: 400; font-style: italic; color: #555;
  }
  /* pz-only spans get personalized timestamps server-side via
     apply_pz_substitutions — keep them visible in print. */
"""

# Performing-physician callout HTML, injected directly under the band-label div.
# The token {{PERFORMING_PHYSICIAN}} is supplied by the adapters from
# physicians.lookup(physician_id)["name_short"].
_PERFORMING_PHYSICIAN_HTML_EN = (
    '    <div class="performing-physician">'
    'Performing physician:<br>{{PERFORMING_PHYSICIAN}}</div>'
)
_PERFORMING_PHYSICIAN_HTML_ES = (
    '    <div class="performing-physician">'
    'Médico que realiza el procedimiento:<br>{{PERFORMING_PHYSICIAN}}</div>'
)


def _inject_personalization_css(text: str) -> str:
    """Append the personalization CSS rules just before </style>."""
    return _replace_unique(
        text,
        "</style>",
        _CSS_APPT_CALLOUT + "</style>",
        where="inject personalization CSS",
    )


# -----------------------------------------------------------------------------
# Combined EGD + colonoscopy English print template.
# -----------------------------------------------------------------------------

_APPT_CALLOUT_HTML_EN = """
<!-- ============================================================= -->
<!-- APPOINTMENT CALLOUT (personalized handout only)               -->
<!-- ============================================================= -->
<section class="appt-callout">
  <div class="appt-line">
    <span class="appt-label">Procedure date:</span> <strong>{{APPT_DATE_HUMAN}}</strong>
    <span class="appt-sep">&bull;</span>
    <span class="appt-label">Arrival:</span> <strong>{{ARRIVAL_TIME}}</strong>
    <span class="appt-sep">&bull;</span>
    <span class="appt-label">Procedure time:</span> <strong>{{APPT_TIME}}</strong>
  </div>
</section>

"""

_APPT_CALLOUT_HTML_ES = """
<!-- ============================================================= -->
<!-- APPOINTMENT CALLOUT (personalized handout only)               -->
<!-- ============================================================= -->
<section class="appt-callout">
  <div class="appt-line">
    <span class="appt-label">Fecha del procedimiento:</span> <strong>{{APPT_DATE_HUMAN}}</strong>
    <span class="appt-sep">&bull;</span>
    <span class="appt-label">Llegada:</span> <strong>{{ARRIVAL_TIME}}</strong>
    <span class="appt-sep">&bull;</span>
    <span class="appt-label">Hora del procedimiento:</span> <strong>{{APPT_TIME}}</strong>
  </div>
</section>

"""


# -----------------------------------------------------------------------------
# Strip the privacy/terms/disclaimer footer from the personalized variants.
# Personalized handouts are clinical print artifacts generated for a specific
# patient appointment — they shouldn't carry the public-website footer (privacy
# policy link, terms of use link, and the generic medical disclaimer aside).
# Public static handouts built directly from the canonical skill templates by
# `make sites` keep the block; only the portal-rendered personalized variants
# strip it.
# -----------------------------------------------------------------------------

_LEGAL_FOOTER_CSS = """.medical-disclaimer {
  margin-top: 16px;
  padding-top: 12px;
  border-top: 1px solid #d0d0d0;
  font-size: 0.85em;
  line-height: 1.45;
  color: #555;
}
@media print {
  .medical-disclaimer {
    color: #333;
    border-top: 1px solid #888;
  }
}

.footer-policy-links {
  margin: 12px 0 8px;
  text-align: center;
  font-size: 0.85em;
}
.footer-policy-links a {
  color: #0e4a82;
  text-decoration: none;
}
.footer-policy-links a:hover { text-decoration: underline; }
.footer-policy-links .sep { color: #999; margin: 0 6px; }

.footer-copyright {
  margin: 6px 0 4px;
  text-align: center;
  font-size: 0.8em;
  color: #888;
}

"""

_LEGAL_FOOTER_HTML_EN = """

<p class="footer-copyright">&copy; 2026</p>
<nav class="footer-policy-links" aria-label="Site policies"><a href="https://giready.com/privacy/">Privacy Policy</a><span class="sep" aria-hidden="true">·</span><a href="https://giready.com/terms/">Terms of Use</a></nav>
<aside class="medical-disclaimer" role="note" aria-label="Medical disclaimer">{{DISCLAIMER}}</aside>

"""

_LEGAL_FOOTER_HTML_ES = """

<p class="footer-copyright">&copy; 2026</p>
<nav class="footer-policy-links" aria-label="Políticas del sitio"><a href="https://giready.com/es/privacidad/">Política de Privacidad</a><span class="sep" aria-hidden="true">·</span><a href="https://giready.com/es/terminos/">Términos de Uso</a></nav>
<aside class="medical-disclaimer" role="note" aria-label="Aviso médico">{{DISCLAIMER}}</aside>

"""


def _strip_legal_footer(text: str, *, lang: str) -> str:
    text = _replace_unique(text, _LEGAL_FOOTER_CSS, "", where=f"strip legal-footer CSS ({lang})")
    html = _LEGAL_FOOTER_HTML_EN if lang == "en" else _LEGAL_FOOTER_HTML_ES
    text = _replace_unique(text, html, "", where=f"strip legal-footer HTML ({lang})")
    return text


def patch_combined_print_en(canonical: str) -> str:
    """Apply the personalization layer to the canonical combined-print.en.html."""
    out = canonical

    # 0. Strip the privacy/terms/disclaimer footer (personalized-only).
    out = _strip_legal_footer(out, lang="en")

    # 1. CSS for appt-callout + performing-physician + followup-callout
    #    (appended pre-</style>).
    out = _inject_personalization_css(out)

    # 1b. Performing-physician callout under the band-label div.
    out = _replace_unique(
        out,
        '<div class="band-label">{{BAND_LABEL}}</div>',
        '<div class="band-label">{{BAND_LABEL}}</div>\n'
        + _PERFORMING_PHYSICIAN_HTML_EN,
        where="combined en: performing-physician callout under band-label",
    )

    # 2. Insert appt-callout section between cover </section> and the LOCATION
    #    section. Anchor on the LOCATION marker comment.
    out = _replace_unique(
        out,
        "<!-- LOCATION -->",
        _APPT_CALLOUT_HTML_EN + "<!-- LOCATION (under the appointment callout) -->",
        where="combined en: appt-callout HTML insertion",
    )

    # 3. Inject the followup placeholder just before the "WHAT ARE THESE
    #    PROCEDURES" section header. We use the multi-line section comment
    #    block as the anchor so we land in the right slot even if the
    #    location section gains internal markup.
    out = _replace_unique(
        out,
        "<!-- ============================================================= -->\n<!-- WHAT ARE THESE PROCEDURES (combined-handout intro)           -->",
        "<!-- Follow-up appointment (narrow standalone callout, personalized) -->\n{{FOLLOWUP_BLOCK_HTML}}\n\n<!-- ============================================================= -->\n<!-- WHAT ARE THESE PROCEDURES (combined-handout intro)           -->",
        where="combined en: followup token before procedures section",
    )

    # 4. Bowel-Prep paragraph: wrap "the day before" inline.
    out = _replace_unique(
        out,
        "The medicines below empty it over the day before.",
        'The medicines below empty it over <span class="pz-only" data-pz-day="-1" data-pz-template="the day before ({date})">the day before</span>.',
        where="combined en: bowel prep 'day before' wrap",
    )

    # 5. Step headings — add data-pz-day + data-pz-suffix attributes.
    out = _replace_unique(
        out,
        '<h2 class="step"><span class="icon">&#128197;</span> 3 Days Before &mdash; Low-Residue Diet</h2>',
        '<h2 class="step" data-pz-day="-3" data-pz-suffix=" &mdash; Low-Residue Diet"><span class="icon">&#128197;</span> 3 Days Before &mdash; Low-Residue Diet</h2>',
        where="combined en: 3-days-before heading",
    )
    out = _replace_unique(
        out,
        '<h2 class="step"><span class="icon">&#128197;</span> 1 Day Before &mdash; Low-Residue Through Lunch</h2>',
        '<h2 class="step" data-pz-day="-1" data-pz-suffix=" &mdash; Low-Residue Through Lunch"><span class="icon">&#128197;</span> 1 Day Before &mdash; Low-Residue Through Lunch</h2>',
        where="combined en: 1-day-before heading",
    )
    out = _replace_unique(
        out,
        '<h2 class="step"><span class="icon">&#128197;</span> Day of Procedure</h2>',
        '<h2 class="step" data-pz-day="0" data-pz-suffix=" &mdash; Day of Procedure"><span class="icon">&#128197;</span> Day of Procedure</h2>',
        where="combined en: day-of heading",
    )

    # 6. Day-of "Clear liquids only after 2 PM the day before."
    out = _replace_unique(
        out,
        "<strong>Clear liquids only after 2 PM the day before.</strong>",
        '<strong>Clear liquids only after 2 PM <span class="pz-only" data-pz-day="-1" data-pz-template="on {date}">the day before</span>.</strong>',
        where="combined en: clear-liquids inline",
    )

    # 7. Meals section: wrap 3 inline phrases.
    out = _replace_unique(
        out,
        "Continue this diet for the 3 days before the procedure, through lunch the day before. After 2:00 PM the day before, switch to clear liquids only",
        'Continue this diet for <span class="pz-only" data-pz-day="-3" data-pz-template="the 3 days before the procedure (starting {date})">the 3 days before the procedure</span>, through lunch <span class="pz-only" data-pz-day="-1" data-pz-template="the day before ({date})">the day before</span>. After 2:00 PM <span class="pz-only" data-pz-day="-1" data-pz-template="on {date}">the day before</span>, switch to clear liquids only',
        where="combined en: meals inline pz spans",
    )

    return BANNER + out


def patch_combined_print_es(canonical: str) -> str:
    """Apply the personalization layer to the canonical combined-print.es.html."""
    out = canonical

    out = _strip_legal_footer(out, lang="es")

    out = _inject_personalization_css(out)

    # Performing-physician callout under the band-label div.
    out = _replace_unique(
        out,
        '<div class="band-label">{{BAND_LABEL}}</div>',
        '<div class="band-label">{{BAND_LABEL}}</div>\n'
        + _PERFORMING_PHYSICIAN_HTML_ES,
        where="combined es: performing-physician callout under band-label",
    )

    out = _replace_unique(
        out,
        "<!-- LOCALIZACIÓN -->",
        _APPT_CALLOUT_HTML_ES + "<!-- LOCALIZACIÓN (bajo el aviso de cita) -->",
        where="combined es: appt-callout HTML insertion",
    )

    out = _replace_unique(
        out,
        "<!-- ============================================================= -->\n<!-- ¿QUÉ SON ESTOS PROCEDIMIENTOS? (intro del folleto combinado)  -->",
        "<!-- Aviso de cita de seguimiento (personalizado) -->\n{{FOLLOWUP_BLOCK_HTML}}\n\n<!-- ============================================================= -->\n<!-- ¿QUÉ SON ESTOS PROCEDIMIENTOS? (intro del folleto combinado)  -->",
        where="combined es: followup token before procedures section",
    )

    out = _replace_unique(
        out,
        "Los medicamentos a continuación lo vacían el día anterior.",
        'Los medicamentos a continuación lo vacían <span class="pz-only" data-pz-day="-1" data-pz-template="el día anterior ({date})">el día anterior</span>.',
        where="combined es: bowel prep 'day before' wrap",
    )

    out = _replace_unique(
        out,
        '<h2 class="step"><span class="icon">&#128197;</span> 3 Días Antes &mdash; Dieta Baja en Residuos</h2>',
        '<h2 class="step" data-pz-day="-3" data-pz-suffix=" &mdash; Dieta Baja en Residuos"><span class="icon">&#128197;</span> 3 Días Antes &mdash; Dieta Baja en Residuos</h2>',
        where="combined es: 3-days-before heading",
    )
    out = _replace_unique(
        out,
        '<h2 class="step"><span class="icon">&#128197;</span> 1 Día Antes &mdash; Baja en Residuos Hasta el Almuerzo</h2>',
        '<h2 class="step" data-pz-day="-1" data-pz-suffix=" &mdash; Baja en Residuos Hasta el Almuerzo"><span class="icon">&#128197;</span> 1 Día Antes &mdash; Baja en Residuos Hasta el Almuerzo</h2>',
        where="combined es: 1-day-before heading",
    )
    out = _replace_unique(
        out,
        '<h2 class="step"><span class="icon">&#128197;</span> Día del Procedimiento</h2>',
        '<h2 class="step" data-pz-day="0" data-pz-suffix=" &mdash; Día del Procedimiento"><span class="icon">&#128197;</span> Día del Procedimiento</h2>',
        where="combined es: day-of heading",
    )

    out = _replace_unique(
        out,
        "<strong>Solo líquidos claros después de las 2 PM del día anterior.</strong>",
        '<strong>Solo líquidos claros después de las 2 PM <span class="pz-only" data-pz-day="-1" data-pz-template="del día ({date})">del día anterior</span>.</strong>',
        where="combined es: clear-liquids inline",
    )

    out = _replace_unique(
        out,
        "Continúe esta dieta durante los 3 días antes del procedimiento, hasta el almuerzo del día anterior. Después de las 2:00 PM del día anterior, cambie a solo líquidos claros",
        'Continúe esta dieta durante <span class="pz-only" data-pz-day="-3" data-pz-template="los 3 días antes del procedimiento (a partir del {date})">los 3 días antes del procedimiento</span>, hasta el almuerzo <span class="pz-only" data-pz-day="-1" data-pz-template="del día anterior ({date})">del día anterior</span>. Después de las 2:00 PM <span class="pz-only" data-pz-day="-1" data-pz-template="del día ({date})">del día anterior</span>, cambie a solo líquidos claros',
        where="combined es: meals inline pz spans",
    )

    return BANNER + out


# -----------------------------------------------------------------------------
# Entry point.
# -----------------------------------------------------------------------------

# (canonical filename, output filename, patch function)
VARIANTS = [
    ("combined-print.en.html", "combined-print-personalized.en.html", patch_combined_print_en),
    ("combined-print.es.html", "combined-print-personalized.es.html", patch_combined_print_es),
]


def main() -> int:
    if not VENDOR_TEMPLATES.exists():
        print(f"FATAL: vendor templates not found at {VENDOR_TEMPLATES}.\n"
              f"Run `make vendor-sync` first.", file=sys.stderr)
        return 1
    OUT_DIR.mkdir(parents=True, exist_ok=True)

    failures: list[str] = []
    for canonical_name, out_name, patch_fn in VARIANTS:
        canonical_path = VENDOR_TEMPLATES / canonical_name
        out_path = OUT_DIR / out_name
        if not canonical_path.exists():
            failures.append(f"{canonical_name}: not found at {canonical_path}")
            continue
        try:
            personalized = patch_fn(canonical_path.read_text(encoding="utf-8"))
        except RuntimeError as e:
            failures.append(f"{canonical_name}: {e}")
            continue
        out_path.write_text(personalized, encoding="utf-8")
        print(f"OK   {out_name}  ({len(personalized):,} bytes)")

    if failures:
        print("\nFAILURES:", file=sys.stderr)
        for f in failures:
            print(f"  - {f}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
